// src/app/home/components/fifth-section/fifth-section.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-fifth-section',
  templateUrl: './fifth-section.component.html',
  styleUrls: ['./fifth-section.component.css']
})
export class FifthSectionComponent {
  constructor() {
  }
}

<section>
  <div class="w-full h-screen bg-gray-800" style="z-index: -2;">
    <div class="relative w-full h-full bg-text">

      <img src="assets/img/pose-1.png" alt="" class="absolute top-0 left-0">
      <img src="assets/img/pose-2.png" alt="" class="absolute top-0 right-0">
      <img src="assets/img/pose-3.png" alt="" class="absolute bottom-0 left-0">
      <img src="assets/img/pose-4.png" alt="" class="absolute bottom-0 right-0">
      <img src="assets/img/hand_1.png" alt="" class="absolute top-64 left-80">
      <img src="assets/img/hand_2.png" alt="" class="absolute top-96 right-80">

      <div class="h-full flex flex-col items-center justify-center" style="z-index: 10;">
        <h4 class="home-title text-center" style="line-height: 1.5;">Try NEAR Promises <br> <span class="bg-gradient-to-r from-blue-400 to-blue-500">right now</span> </h4>  <br>
        <a routerLink="/dashboard" class="btn-blue mt-8 text-white">Go to dashboard</a>
      </div>

    </div>
  </div>
</section>

// src/components/FifthSection.vue
<template>
  <section>
        <div class="w-full h-screen bg-gray-800" style="z-index: -2;">
            <div class="relative w-full h-full bg-text">

                <img src="@/assets/img/pose-1.png" alt="" class="absolute top-0 left-0">
                <img src="@/assets/img/pose-2.png" alt="" class="absolute top-0 right-0">
                <img src="@/assets/img/pose-3.png" alt="" class="absolute bottom-0 left-0">
                <img src="@/assets/img/pose-4.png" alt="" class="absolute bottom-0 right-0">
                <img src="@/assets/img/hand_1.png" alt="" class="absolute top-64 left-80">
                <img src="@/assets/img/hand_2.png" alt="" class="absolute top-96 right-80">

                <div class="h-full flex flex-col items-center justify-center" style="z-index: 10;">
                    <h4 class="home-title text-center" style="line-height: 1.5;">Try NEAR Promises <br> <span class="bg-gradient-to-r from-blue-400 to-blue-500">right now</span> </h4>  <br>
                    <a href="#" class="btn-blue mt-8 text-white">Go to dashboard</a>
                </div>

            </div>
        </div>
    </section>
</template>

<script>
export default {

}
</script>
