// src/app/home/components/second-section/second-section.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-second-section',
  templateUrl: './second-section.component.html',
  styleUrls: ['./second-section.component.css']
})
export class SecondSectionComponent {
  constructor() {
  }
}

<section id="about">
  <div class="relative w-full bg-gray-800 text-white section-shadow">

    <div class="absolute top-0 right-0 lg:w-2/3 2xl:w-1/2">
      <img src="assets/img/Screens.png" alt="" class="w-full hidden lg:block">
    </div>

    <div class="container mx-auto py-16 h-637">
      <div class="flex flex-col lg:flex-row">

        <!-- About tracker text -->
        <div class="w-full lg:w-2/5 px-6">
          <h2 class="home-title">About <span class="bg-gradient-to-r from-blue-400 to-blue-500">trecker</span></h2>
          <p class="text-gray-400 mt-10 lg:mt-4 leading-relaxed">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Etiam viverra hac a aliquam. Turpis id dictum elementum
            pellentesque tellus sagittis. Accumsan pretium auctor
            pellentesque purus faucibus. Ac quis aliquam eleifend
            pulvinar porttitor. Amet id pharetra eu sem purus. Lorem
            ipsum dolor sit amet, consectetur adipiscing elit. Etiam
            viverra hac a aliquam. Turpis id dictum elementum
            pellentesque tellus sagittis. Accumsan pretium auctor
            pellentesque purus faucibus. Ac quis aliquam eleifend
            pulvinar porttitor. Amet id pharetra eu sem purus.
          </p>
        </div>

        <!-- About tracker img -->
        <div class="w-full lg:w-2/3">
          <img src="assets/img/Screens.png" alt="" class=" lg:hidden">
        </div>
      </div>

    </div>
  </div>
</section>

// src/components/SecondSection.vue
<template>
  <section>
        <div class="relative w-full bg-gray-800 text-white section-shadow">

            <div class="absolute top-0 right-0 lg:w-2/3 2xl:w-1/2">
                <img src="@/assets/img/Screens.png" alt="" class="w-full hidden lg:block">
            </div>

            <div class="container mx-auto py-16 h-637">
                <div class="flex flex-col lg:flex-row">

                    <!-- About tracker text -->
                    <div class="w-full lg:w-2/5 px-6">
                        <h2 class="home-title">About <span class="bg-gradient-to-r from-blue-400 to-blue-500">trecker</span></h2>
                        <p class="text-gray-400 mt-10 lg:mt-4 leading-relaxed">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                            Etiam viverra hac a aliquam. Turpis id dictum elementum 
                            pellentesque tellus sagittis. Accumsan pretium auctor 
                            pellentesque purus faucibus. Ac quis aliquam eleifend 
                            pulvinar porttitor. Amet id pharetra eu sem purus. Lorem 
                            ipsum dolor sit amet, consectetur adipiscing elit. Etiam 
                            viverra hac a aliquam. Turpis id dictum elementum 
                            pellentesque tellus sagittis. Accumsan pretium auctor 
                            pellentesque purus faucibus. Ac quis aliquam eleifend 
                            pulvinar porttitor. Amet id pharetra eu sem purus. 
                        </p>
                    </div>

                    <!-- About tracker img -->
                    <div class="w-full lg:w-2/3">
                        <img src="@/assets/img/Screens.png" alt="" class=" lg:hidden">
                    </div>
                </div>

            </div>
        </div>
    </section>
</template>

<script>
export default {

}
</script>
