// src/components/ThirdSection.vue
<template>
  <section id="receive">
        <div class="bg-gray-800 text-white">
            <div class="w-full bg-text">
                <div class="container mx-auto px-6 py-32">
                    <h3 class="home-title text-center">What you <span class="bg-gradient-to-r from-blue-400 to-blue-500">recieve</span> </h3>

                    <div class="flex items-center flex-col lg:flex-row mt-12">

                        <!-- Blue circle -->
                        <div class="flex justify-center items-center w-72 px-6 h-72 rounded-full bg-gradient-to-r from-blue-400 to-blue-500">
                            <p class="font-bold text-3xl text-center">Promise trecker</p>
                        </div>

                        <!-- Green circle -->
                        <div class="flex justify-center items-center mt-4 ml-4 xl:ml-60 px-6 w-44 h-44 rounded-full bg-gradient-to-r from-green-400 to-green-500">
                            <p class="font-bold text-2xl text-center">Promises progress journal </p>
                        </div>

                        <!-- Orange circle -->
                        <div class="flex justify-center items-center mt-4 -ml-4 lg:ml-16 px-6 w-60 md:w-72 h-60 md:h-72 rounded-full bg-gradient-to-br from-orange-400 to-orange-500">
                            <p class="font-bold text-3xl text-center">Motivation to do promises</p>
                        </div>

                    </div>

                    <div class="flex items-center flex-col lg:flex-row lg:mt-12">

                        <!-- Purple circle -->
                        <div class="flex justify-center items-center mt-12 px-6 xl:w-72 h-52 w-52  xl:h-72 rounded-full bg-gradient-to-b from-purple-400 to-purple-500">
                            <p class="font-bold text-3xl text-center">Promise trecker</p>
                        </div>

                        <!-- Pink-purple circle -->
                        <div class="flex justify-center items-center mt-12 lg:-mt-32 xl:-mt-80 px-6 ml-16 lg:ml-12 w-44 md:w-72 h-44 md:h-72 rounded-full bg-gradient-to-b from-pink-400 to-purple-500">
                            <p class="font-bold text-2xl text-center">Promise reminder </p>
                        </div>

                        <!-- Orange circle -->
                        <div class="flex justify-center items-center mt-8 lg:mt-0 w-56 lg:w-72 xl:w-96 h-56 lg:h-60 xl:h-96 px-6 rounded-full bg-gradient-to-br from-yellow-700 to-yellow-500">
                            <p class="font-bold text-2xl md:text-3xl text-center">Oppourtunity to check your friends promises</p>
                        </div>

                        <!-- Blue circle -->
                        <div class="flex justify-center items-center -ml-4 lg:ml-28 px-6 mt-12 lg:-mt-32 w-72 h-72 rounded-full bg-gradient-to-r from-blue-400 to-blue-500">
                            <p class="font-bold text-3xl text-center">Self-development to do promises</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script>
export default {

}
</script>

// src/app/home/components/third-section/third-section.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-third-section',
  templateUrl: './third-section.component.html',
  styleUrls: ['./third-section.component.css']
})
export class ThirdSectionComponent {
  constructor() {
  }
}

<section id="receive">
  <div class="bg-gray-800 text-white">
    <div class="w-full bg-text">
      <div class="container mx-auto px-6 py-32">
        <h3 class="home-title text-center">What you <span class="bg-gradient-to-r from-blue-400 to-blue-500">recieve</span> </h3>

        <div class="flex items-center flex-col lg:flex-row mt-12">

          <!-- Blue circle -->
          <div class="flex justify-center items-center w-72 px-6 h-72 rounded-full bg-gradient-to-r from-blue-400 to-blue-500">
            <p class="font-bold text-3xl text-center">Promise trecker</p>
          </div>

          <!-- Green circle -->
          <div class="flex justify-center items-center mt-4 ml-4 xl:ml-60 px-6 w-44 h-44 rounded-full bg-gradient-to-r from-green-400 to-green-500">
            <p class="font-bold text-2xl text-center">Promises progress journal </p>
          </div>

          <!-- Orange circle -->
          <div class="flex justify-center items-center mt-4 -ml-4 lg:ml-16 px-6 w-60 md:w-72 h-60 md:h-72 rounded-full bg-gradient-to-br from-orange-400 to-orange-500">
            <p class="font-bold text-3xl text-center">Motivation to do promises</p>
          </div>

        </div>

        <div class="flex items-center flex-col lg:flex-row lg:mt-12">

          <!-- Purple circle -->
          <div class="flex justify-center items-center mt-12 px-6 xl:w-72 h-52 w-52  xl:h-72 rounded-full bg-gradient-to-b from-purple-400 to-purple-500">
            <p class="font-bold text-3xl text-center">Promise trecker</p>
          </div>

          <!-- Pink-purple circle -->
          <div class="flex justify-center items-center mt-12 lg:-mt-32 xl:-mt-80 px-6 ml-16 lg:ml-12 w-44 md:w-72 h-44 md:h-72 rounded-full bg-gradient-to-b from-pink-400 to-purple-500">
            <p class="font-bold text-2xl text-center">Promise reminder </p>
          </div>

          <!-- Orange circle -->
          <div class="flex justify-center items-center mt-8 lg:mt-0 w-56 lg:w-72 xl:w-96 h-56 lg:h-60 xl:h-96 px-6 rounded-full bg-gradient-to-br from-yellow-700 to-yellow-500">
            <p class="font-bold text-2xl md:text-3xl text-center">Oppourtunity to check your friends promises</p>
          </div>

          <!-- Blue circle -->
          <div class="flex justify-center items-center -ml-4 lg:ml-28 px-6 mt-12 lg:-mt-32 w-72 h-72 rounded-full bg-gradient-to-r from-blue-400 to-blue-500">
            <p class="font-bold text-3xl text-center">Self-development to do promises</p>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>
